### ISSUE TITLE
解锁模块限制

### ISSUE THREAD

**Issue by nasa565** [ravizhan/xiyou_crack#1]
目前自动修改分数模块只能用于专项训练或考试，能否用于其他模块，例如特训之类

**Comment by ravizhan** [comment]
应该没啥问题，等个一两天吧，这东西有点久远了
我是真没想到会有人用😂，所以完全按照自己需求来的

**Comment by ravizhan** [comment]
v0.0.5已修复 应该很快就会收到推送了
有什么问题还请及时反馈

**Comment by nasa565** [comment]
刚刚测试了一下，没有什么大问题，挺厉害的
